// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Shadow.Lang {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Shadow.Lang.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        public static string ErrorSavingPaired {
            get {
                return ResourceManager.GetString("ErrorSavingPaired", resourceCulture);
            }
        }
        
        public static string lblAuthenticating {
            get {
                return ResourceManager.GetString("lblAuthenticating", resourceCulture);
            }
        }
        
        public static string lblValidating {
            get {
                return ResourceManager.GetString("lblValidating", resourceCulture);
            }
        }
        
        public static string lblRegistering {
            get {
                return ResourceManager.GetString("lblRegistering", resourceCulture);
            }
        }
        
        public static string lblGettingLocation {
            get {
                return ResourceManager.GetString("lblGettingLocation", resourceCulture);
            }
        }
        
        public static string lblLookingUpAddress {
            get {
                return ResourceManager.GetString("lblLookingUpAddress", resourceCulture);
            }
        }
        
        public static string DefaultMessage1 {
            get {
                return ResourceManager.GetString("DefaultMessage1", resourceCulture);
            }
        }
        
        public static string DefaultMessage2 {
            get {
                return ResourceManager.GetString("DefaultMessage2", resourceCulture);
            }
        }
        
        public static string BtnOK {
            get {
                return ResourceManager.GetString("BtnOK", resourceCulture);
            }
        }
        
        public static string BtnScan {
            get {
                return ResourceManager.GetString("BtnScan", resourceCulture);
            }
        }
        
        public static string BtnPair {
            get {
                return ResourceManager.GetString("BtnPair", resourceCulture);
            }
        }
        
        public static string BtnUnpair {
            get {
                return ResourceManager.GetString("BtnUnpair", resourceCulture);
            }
        }
        
        public static string lblWelcome_Tagline {
            get {
                return ResourceManager.GetString("lblWelcome_Tagline", resourceCulture);
            }
        }
        
        public static string lblWelcome_TCAgree {
            get {
                return ResourceManager.GetString("lblWelcome_TCAgree", resourceCulture);
            }
        }
        
        public static string btnWelcome_CreateAccount {
            get {
                return ResourceManager.GetString("btnWelcome_CreateAccount", resourceCulture);
            }
        }
        
        public static string lblWelcome_SignIn {
            get {
                return ResourceManager.GetString("lblWelcome_SignIn", resourceCulture);
            }
        }
        
        public static string lblWelcome_NoShadowDevice {
            get {
                return ResourceManager.GetString("lblWelcome_NoShadowDevice", resourceCulture);
            }
        }
        
        public static string lblWelcome_BuyNow {
            get {
                return ResourceManager.GetString("lblWelcome_BuyNow", resourceCulture);
            }
        }
        
        public static string phWelcome_EnterEmailAddress {
            get {
                return ResourceManager.GetString("phWelcome_EnterEmailAddress", resourceCulture);
            }
        }
        
        public static string phWelcome_CreatePassword {
            get {
                return ResourceManager.GetString("phWelcome_CreatePassword", resourceCulture);
            }
        }
        
        public static string lblContactsPage_Contacts {
            get {
                return ResourceManager.GetString("lblContactsPage_Contacts", resourceCulture);
            }
        }
        
        public static string lblContactsPage_AddContacts {
            get {
                return ResourceManager.GetString("lblContactsPage_AddContacts", resourceCulture);
            }
        }
        
        public static string btnContactsPage_Finish {
            get {
                return ResourceManager.GetString("btnContactsPage_Finish", resourceCulture);
            }
        }
        
        public static string lblContactsPage_EmergencyContacts {
            get {
                return ResourceManager.GetString("lblContactsPage_EmergencyContacts", resourceCulture);
            }
        }
        
        public static string lblContactsPage_AddContact {
            get {
                return ResourceManager.GetString("lblContactsPage_AddContact", resourceCulture);
            }
        }
        
        public static string lblEmergencyMessage_Title {
            get {
                return ResourceManager.GetString("lblEmergencyMessage_Title", resourceCulture);
            }
        }
        
        public static string lblEmergency_ChooseMessage {
            get {
                return ResourceManager.GetString("lblEmergency_ChooseMessage", resourceCulture);
            }
        }
        
        public static string btnEmergencyMessage_Continue {
            get {
                return ResourceManager.GetString("btnEmergencyMessage_Continue", resourceCulture);
            }
        }
        
        public static string btnEmergencyMessage_Back {
            get {
                return ResourceManager.GetString("btnEmergencyMessage_Back", resourceCulture);
            }
        }
        
        public static string lblEmergency_MessageTitle {
            get {
                return ResourceManager.GetString("lblEmergency_MessageTitle", resourceCulture);
            }
        }
        
        public static string btnEmergency_Preview {
            get {
                return ResourceManager.GetString("btnEmergency_Preview", resourceCulture);
            }
        }
        
        public static string btnEmergency_Default {
            get {
                return ResourceManager.GetString("btnEmergency_Default", resourceCulture);
            }
        }
        
        public static string lblSignupLocation_Title {
            get {
                return ResourceManager.GetString("lblSignupLocation_Title", resourceCulture);
            }
        }
        
        public static string lblSignupDevicePage_DeviceList {
            get {
                return ResourceManager.GetString("lblSignupDevicePage_DeviceList", resourceCulture);
            }
        }
        
        public static string lblSignupDevicePage_btnScan {
            get {
                return ResourceManager.GetString("lblSignupDevicePage_btnScan", resourceCulture);
            }
        }
        
        public static string lblMain_AppTitle {
            get {
                return ResourceManager.GetString("lblMain_AppTitle", resourceCulture);
            }
        }
    }
}
